version: '2'
services:
    ydt-app:
        image: ydt
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ydt-mysql:3306/ydt?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ydt-mysql:
        extends:
            file: mysql.yml
            service: ydt-mysql
